### ISSUE TITLE
Excessive depth in document error causing issues for dependent package rNOMADS

### ISSUE THREAD

**Issue by dannycbowman** [hadley/xml2#70] opened 2016-01-22 17:48 UTC
I maintain the rNOMADS package, which relies on xml2 to parse large lists of web-hosted files.  Unfortunately, attempts to retrieve some file list fails with

    Error: Excessive depth in document: 256 use XML_PARSE_HUGE option [1]

I have spent a great deal of time attempting to reset this depth in order to permit my users to download the data they need.  However, I believe this depth is hard coded and thus can't be changed.  This is a serious issue for the proper functioning of my package.  The only work around I can provide is to ask my users to download a forked version of xml2 that is not available on CRAN:

    library(drat)
    drat:::add("shabbychef")
    install.packages('xml2'

Would it be possible to implement shabbychef's fix in the official xml2 repository, so I can easily make it available to my users?
To reproduce error:

    library(xml2)
    library(lubridate)

    date.today <- format(now(tz = "UTC"), "%Y%m%d")
    url <- paste0("http://nomads.ncep.noaa.gov/cgi-bin/filter_rap.pl?dir=%2Frap.", date.today)
    xml2::read_html(url)

**Comment by hadley** [comment] 2016-05-04 18:26
Do you want to submit a pull request?

**Comment by jimhester** [comment] 2016-05-12 20:58
This is a dupe of #62

**Closed** 2016-05-12 22:28 UTC
